server:
  port: 8083
  servlet:
    context-path: /ad-sponsor

spring:
  application:
    name: ad-sponsor
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  data:
    neo4j:
      open-in-view: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/youzan-ad?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/


